### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by rotweiss4** [RDG88/lovelace-awtrix-light-display-card#1]
Hi,

can you give me a hint how to install the card?

I can't do it.  Extracting the card as a zip file in custom_component does not work.  The card is not found in lovelace.

If i try it via URL to add a custom repository to HACS i got also an error

Thanks a lot.

**Comment by RDG88** [comment]
Just add a custom repository in HACS with 

URL: https://github.com/RDG88/lovelace-awtrix-light-display-card
Category: Lovelace

Then you are able to install AWTRIX Light Display Card in HACS.

See also for reference: https://hacs.xyz/docs/faq/custom_repositories/

Please let me know what error you get..?

**Comment by rotweiss4** [comment]
Crazy, I tried exactly this and got an error.  Now it's working.  Thank you. 👍🏼
